blank_issues_enabled: true
contact_links:
  - name: Discord Server
    about: Comming Soon...
  - name: Wiki / Dokumentation
    url: https://github.com/TheMRX13/MC-Adventure-Tech/wiki
    about: Schau in unserem Wiki nach Anleitungen und Informationen
