blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://discord.gg/dein-server
    about: FÃ¼r allgemeine Fragen und Diskussionen besuche unseren Discord
  - name: Wiki / Dokumentation
    url: https://github.com/TheMRX13/MC-Adventure-Tech/wiki
    about: Schau in unserem Wiki nach Anleitungen und Informationen
